jobs:
  - name: u14
    type: runSh
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14"
              imageTag: master
          script:
            
             - java -version  
             - nodejs --version
             - yarn -version
             - source /usr/local/rvm/scripts/rvm
             - ruby -v
             - python -V
             - pip --version
             - virtualenv --version
             - git --version
             - aws --version
             - az --version
             - jfrog --version
             - gcloud version
             - git lfs version
             - kubectl version --client
             - kops version
             - helm version --client
             - doctl version
             - ansible --version
             - pip show boto
             - pip show boto3
             - pip show apache-libcloud
             - pip show azure
             - pip show dopy
             - packer --version
             - jq --version
             - terraform --version
             - openstack --version
             - eb --version
             - npm --version
  - name: u14-services_runCI
    type: runCI
    steps:
      - IN: u14-services_ciRepo             
      - IN: u14   
  - name: u14go-ci_runCI
    type: runCI
    steps:
      - IN: u14go-ci_ciRepo  
      - IN: u14-services_runCI
  - name: u14pytall-ci_runCI
    type: runCI
    steps:
      - IN: u14pytall-ci_ciRepo 
      - IN: u14-services_runCI
  - name: u14php-ci_runCI
    type: runCI
    steps:
      - IN: u14php-ci_ciRepo
      - IN: u14-services_runCI
  - name: u14scala-ci_runCI
    type: runCI
    steps:
      - IN: u14scala-ci_ciRepo 
      - IN: u14-services_runCI
  - name: u14node-ci_runCI
    type: runCI
    steps:
      - IN: u14node-ci_ciRepo 
      - IN: u14-services_runCI
  - name: u14clo-ci_runCI
    type: runCI
    steps:
      - IN: u14clo-ci_ciRepo 
      - IN: u14-services_runCI
  - name: u14cpp-ci_runCI
    type: runCI
    steps:
      - IN: u14cpp-ci_ciRepo
      - IN: u14-services_runCI
  - name: u14javall-ci_runCI
    type: runCI
    steps:
      - IN: u14javall-ci_ciRepo
      - IN: u14-services_runCI
  - name: u14rub-ci_runCI
    type: runCI
    steps:
      - IN: u14rub-ci_ciRepo 
      - IN: u14-services_runCI
